version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  backend:
    build: ./backend
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db

  db:
    image: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
