version: "3.9"

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup frontend backend db redis
  frontend:
    build: .
    ports:
      - "5173:5173"
    env_file:
      - ./frontend.env
    networks:
      shared:
        aliases:
          - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "8085:8085"
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/backend.env
    environment:
      POSTGRES_HOST: db
    networks:
      shared:
        aliases:
          - backend
    command: bash -c "sleep 2 && ./main"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres", "-h", "0.0.0.0"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      shared:
        aliases:
          - db

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
      REDIS_DB: 1
    networks:
      shared:
        aliases:
          - redis

networks:
  shared:
